//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace tntt
{


    public partial class LamBai
    {
        protected global::System.Web.UI.WebControls.Label Label2;
        public new tntt.SiteMaster Master
        {
            get
            {
                return ((tntt.SiteMaster)(base.Master));
            }
        }
    }
}
